<Project>
	<!-- Force unified output dirs for ALL projects in the solution 												-->
		<!--	<PropertyGroup>																												-->
			<!-- 	<ArchName Condition="'$(Platform)'=='x64'">x86_64</ArchName>			-->
			<!-- 	<ArchName Condition="'$(Platform)'=='Win32'">x86</ArchName>				-->
			<!-- 	<ArchName Condition="'$(Platform)'=='ARM64'">arm64</ArchName>		-->
	
			<!-- "x86_64\Debug\Voila"  																																												-->
			<!--		<OutDir>	$(SolutionDir)Binaries\$(ArchName)\$(Configuration)\$(MSBuildProjectName)\								</OutDir>		-->
			<!--		<IntDir>		$(SolutionDir)Binaries\Intermediates\$(ArchName)\$(Configuration)\$(MSBuildProjectName)\		</IntDir>		-->
		<!--		</PropertyGroup> 																																														-->
  
  <!-- "Link Library Dependencies = Yes" everywhere 																				-->
  <!-- This must be here because premake fucked us and the engine wont make a lib without this 	-->
  <!-- CURSE YOU VISUAL STUDIO 																												-->
  <ItemDefinitionGroup>
    <ProjectReference>
      <LinkLibraryDependencies>true</LinkLibraryDependencies>
    </ProjectReference>
  </ItemDefinitionGroup>
</Project>