<Project>
  <Target Name="CopySDLDll" AfterTargets="Build"
          Condition="'$(MSBuildProjectName)'=='Example'">
    <ItemGroup>
      <SDLDll Include="$(MSBuildThisFileDirectory)Lib\$(Configuration)\SDL\SDL3.dll" />
    </ItemGroup>

    <Copy SourceFiles="@(SDLDll)"
          DestinationFolder="$(TargetDir)"
          SkipUnchangedFiles="true"
          Condition="Exists('%(SDLDll.FullPath)')" />
  </Target>
</Project>
